# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1d71a06cfed353072911a1c52df5eab4e6be62491c9e1b9cfe6413f61a7080499611bbb8ec481f612c59aca245ef1eb2de66cf973516fd63d585698338cae4

test:
  secret_key_base: 1526960b6c56f548e34e2fb5ff22f3a207025623839654d8f52f7e2b0096e4de0f0e318e7cd8cda974e39e92c10298ec8249aa1adb6ef5a6dde3fb0538eaaea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
